### ISSUE TITLE
TypeError: this is not a constructor

### ISSUE THREAD

**Issue by Steviey** [Vincit/objection.js#221]
I get the following error trying an insert in a class **(insertData(argsObj))**...any ideas?

TypeError: this is not a constructor
    at Function.fromJson (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\model\ModelBase.js:520:17)
    at Function.ensureModel (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\model\Model.js:607:25)
    at Function.ensureModelArray (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\model\Model.js:632:20)
    at InsertOperation.call (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\queryBuilder\operations\InsertOperation.js:55:40)
    at QueryBuilder.callQueryBuilderOperation (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\queryBuilder\QueryBuilderBase.js:349:19)
    at QueryBuilder.insert (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\queryBuilder\QueryBuilder.js:1098:17)
    at QueryBuilder.decorator$writeQueryOperation [as insert] (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\queryBuilder\QueryBuilder.js:1343:12)
    at PslSqliteDb.insertData (file:///C:/0000_TRANSFER/HTML5/SQLITE3_ORM/js/PslSqliteDb.js:89:35)
From previous event:
    at QueryBuilder.execute (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\queryBuilder\QueryBuilder.js:780:20)
    at QueryBuilder._catch [as catch] (C:\0000_TRANSFER\HTML5\SQLITE3_ORM\node_modules\objection\lib\queryBuilder\QueryBuilder.js:614:24)
    at PslSqliteDb.insertData (file:///C:/0000_TRANSFER/HTML5/SQLITE3_ORM/js/PslSqliteDb.js:92:19)
    at file:///C:/0000_TRANSFER/HTML5/SQLITE3_ORM/js/invokeDummy.js:8:8

```
class SqliteDb {
    constructor(argsObj) {
        this.Model = require('objection').Model;
        //let objection = require('objection');
        this.Knex  = require('knex');
        this.knex  = {};
        this.sortableTimestamp = Math.floor(Date.now() / 1000);
        this.defaultDateTime    = null;
        this.schemaPromise      = {}
    }
    extendModel(argsObj) {
        this.Model.extend(this.MinimalModel);
        this.MinimalModel.tableName = argsObj.tableName; 
        return;
    }
    MinimalModel() {
        this.Model.apply(this, arguments);
        return;
    }
    createDatabase(argsObj) {
        // Initialize knex connection.
        this.knex = this.Knex({
            client: 'sqlite3',
            connection: { filename: argsObj.dBName },
            useNullAsDefault: true
        });
        this.defaultDateTime = this.knex.fn.now();
        // Give the connection to objection.
        this.Model.knex(this.knex);
        return;
    }
    createTable(argObj) {
        this.schemaPromise = this.knex.schema.createTableIfNotExists(argObj.tableName, function (table) {
            table.increments('id').primary();
            //table.dropColumn('firstName');
            table.string('firstname');
            table.string('surname');
            table.text('comment');
            table.timestamp('gendate').defaultTo(this.defaultDateTime);
            table.timestamp('editdate').defaultTo(this.defaultDateTime);
            table.string('sortabletimestamp');
        })
        //.debug()
        //.then(function (selected) {console.log(selected)})
        .catch(function (err) { console.log(err.stack)})
        return;
    }
    test(){

        return this.sortableTimestamp;
    }

    insertData(argsObj) {
        console.log(this.sortableTimestamp);
        var insertObj = {
            firstname: 'Mal sehen',
            surname: 'Meier',
            comment: 'Ein Test',
            sortabletimestamp: this.sortableTimestamp
        };
        this.MinimalModel.query().insert(insertObj)
            //.debug()
            //.then(function (numUpdated) {console.log(numUpdated);})
            .catch(function (err) {console.log(err.stack)});
        return;
    }

    selectData(argsObj) {
        //return res;
    }

```

**Comment by elhigu** [comment]
I'm pretty sure its nothing that has anything to do with objection. Please try to ask specific questions with complete code to reproduce those problems.

**Comment by Steviey** [comment]
If it would not, then there would be no relationship.

**Comment by fl0w** [comment]
@Steviey Please beware that this forum is *mainly* for discussion, bug reporting and feature introspection for the `objection.js` library. While it's okay to ask questions, this is not a chat nor a forum to post every error you encounter.

Most questions you've posted thus far have been solved by yourself - meaning that given enough time, you're fully capable to figuring out issues you're encountering yourself. This is a good thing! This is how learning is supposed to be. We all get stuck however, and yet we do not post a new issue for every error we encounter - Especially when the problem might not at all be related to the library itself to begin with.

You need to give it a little brainpower before throwing the problem onto others.

A few notes to make helping easier.
  1. Make sure the problem you're encountering is related to the library (in this case, `objection.js`) before posting an issue.
  1. Try to break down your problem to a minimal, reproducible example. Preferably something that others can copy and paste into a `.js`-file or even node CLI.
  1. Try to exclude any other library (not related to `objection.js`), for your own sake. Others might not bother to help if less time was spent creating the issue then it takes to read it. Most authors watch many libraries and tools on Github. Be respectful to those offering help by putting some effort into your issue report.
  1. Use Google (or your preferred search engine), and learn to really use it. Most of us wouldn't even have a job without the power of finding the answer ourselves.
  1. Consider joining a chat, board or a forum dedicated for help. There's tons out there, from Reddit to StackOverflow to IRC. Google it!
  1. When you're paste:ing code, add `js` after three backticks (\`). It'll colorise the output. It invites others to look at your code. And while on the subject, try to keep your indentation concise.
```js
const objection = require('objection')

class MyModel extends objection.Model {}

function uselessExample () {
  return Model
    .query()
    .where({
      foo: 'bar',
      jennifer: 'Lawrence'
   })
}
```
See? Isn't that just so much easier to look at?

Happy coding!

**Comment by Steviey** [comment]
@flOw thank you for your advice. I'm googling and searching for hours now.  
Where can I chat for this specific issue? I have read the documentations again and again. Mainly here: 
http://vincit.github.io/objection.js/#models
The problem is, I still don't understand how to implement the model in a class, so that I can run an insert query on the model object. Once I understand that I can do CRUD and I will never ask again for a long long time. I tried every variation I could imagine.

**Comment by elhigu** [comment]
@Steviey Try to run this example project and study how it works https://github.com/Vincit/objection.js/tree/master/examples/express-es6

**Comment by Steviey** [comment]
@elhigu Thank you. Regarding to this https://github.com/Vincit/objection.js/blob/master/examples/express-es6/models/Animal.js
all what I want to do is to add an animal from an external class.

**Comment by elhigu** [comment]
@Steviey just run that example, play with it, study what every part of code of that example is doing and you will learn everything that is needed for CRUD. 

I'm pretty sure that 5 minutes of looking that is not long enough to understand the whole example project... I'm sorry, but I don't think that I can help you more than just this (pointing to a complete CRUD example project).

**Comment by Steviey** [comment]
I'm sure there is a much easier way to do this. And my project will use many other libraries. 
So there is no need to blast it with actually unnecessary parts and knowledge (doing CRUD since 20 years now). I also did not saw all this as official requirements/dependencies for objection.js.

**Comment by Steviey** [comment]
Finally got it after 10 hours of hassle.
3 lines of code possibly to easy to communicate...
       ```JavaScript
 constructor(argsObj) {
        this.Model           = require('objection').Model;
        this.Model.tableName = argsObj.tableName;
```

**Comment by elhigu** [comment]
Looks like you didn't read that example project code after all... anyone looking this this issue *please don't create your models like this*.
